---
title: "My First Blog Post"
description: |
  First blog post for this website.
author:
  - name: Paloma Cartwright
date: 08-10-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I will add actual information later, but for now, enjoy this hippie ipsum. 

Acaiberries gojiberries acid LSD ayahuasca acroyoga activatedcharcoal acunpuncture innatecapacity co-create, cleansing spiritualawakening hackysack lifecoach soulmate continuum aries. LSD conflictresolution indigenouselders mayancalendar manifestation discoveringvaluabletruths synchronicity plantconsciousness, embracingandmovingtowards prius backjack innatecapacity trippingon short-grainbrownrice entheogen, ganja reprogrammingyourDNA deeptissue kefir ayahuasca humanpotential. Impermanent acunpuncture sciencehasproventhat herbaltea honoringyourtruth breathwork ponytail somatic firetending, thebuddha toendsuffering empoweringmessages whitesage worldpeace maypole. Cleansing toendsuffering rawthenticself quinoa shanti reflexology familyconstellation withadashofcayennepepper, ponytail kirtan personaldevelopment all-natural coldplunge shakti, thepowerofintention bodyworker fertilityawareness indigenouselders radicalacceptance nonprofit salvia, shiva pisces mastercleanse astrological ritesofpassage. Pittaimbalance thedalilama raindance giftingcircle authenticself sungazing, cuddleparty open-minded sharing craniosacraltherapy feelingtriggered, shamanicceremony equinox holdingspace quinoa.
